version: 2

jobs:
  build:
    working_directory: ~/super-basic-auth
    docker:
      - image: circleci/php:7.1-cli
    steps:
      - checkout
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer install --no-progress --no-interaction --prefer-dist
      - run: ./vendor/bin/phpunit
